name: Android build

on: push

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      # Setup environment
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # Install dependencies
      - name: Install app dependencies
        run: npm install

      # Build app
      - name: Build Angular
        run: ionic build --prod

      - name: Copy files to native project
        run: cap sync android

      - name: Clean android project
        run: android/gradlew --project-dir android clean

      - name: Build Android APK
        run: android/gradlew --project-dir android build

      # Publish artifacts
      - name: Upload dev APK
        uses: actions/upload-artifact@v1
        with:
          name: app-dev
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
